"use client";

import Head from 'next/head'
import Link from 'next/link'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <div id="wrapper">
            <div className="header">
              <div className="introduction">
                <div className="informacion">
                  <h3>hi!</h3>
                  <div className="linea-animada"></div>
                  <h1 data-scroll data-scroll-speed="1">
                    I'm
                  </h1>
                  <h1 id="nombre">Patricio J.C.</h1>
                  <p id="resumen">
                    Graphic Designer <br />
                    UX/UI Designer
                  </p>
                  <p id="sobremi"></p>
                </div>
                <div className="imagen-introduction">
                  <img src="/img/imgintrobn.jpg" alt="" />
                  <img src="/img/imgintrosil.png" alt="" />
                </div>
              </div>
            </div>
            <div className="main">
              <div className="selected-works">
                <h1>
                  selected <b>works</b>
                </h1>
                <section className="branding">
                  <h1>_branding</h1>
                  <div className="branding-container">
                    <div className="brand1">
                      <Link href="/work">
                        <img src="/img/Hookout1.jpg" alt="" />
                      </Link>
                    </div>
                    <div className="brand2">
                      <Link href="/work">
                        <img src="/img/Rest1.jpg" alt="" />
                      </Link>
                    </div>
                  </div>
                </section>
                <section className="advertising">
                  <h1>_advertising</h1>
                  <div className="mkt-container">
                    <div className="mkt1">
                      <Link href="/work">
                        <img src="/img/Bershka3.jpg" alt="" />
                      </Link>
                    </div>
                    <div className="mkt2">
                      <Link href="/work">
                        <img src="/img/PrimeVideo2.jpg" alt="" />
                      </Link>
                    </div>
                  </div>
                </section>
                <section className="illustration">
                  <h1>_illustrations</h1>
                  <div className="illust-container">
                    <div className="ill1">
                      <Link href="/work">
                        <img src="/img/RelsB.jpg" alt="" />
                      </Link>
                    </div>
                    <div className="ill2">
                      <Link href="/work">
                        <img src="/img/Nathy_Peluso.png" alt="" />
                      </Link>
                    </div>
                  </div>
                </section>
                <div className="texto-final">
                  <p>
                    ...and more{" "}
                    <Link href="/work">
                      <strong>works</strong>
                    </Link>{" "}
                    here
                  </p>
                </div>
              </div>
              <div className="lets-talk-contact">
                <img src="/img/bicileta-gif.gif" alt="" />
                <p>
                  Let's work together!{" "}
                  <Link href="/contact" className="btn-effect2">
                    Contact me
                  </Link>
                </p>
              </div>
            </div>
          </div>
    </div>
  )
}
